version: "2"

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    # install python package before building the doc
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
